name: Build and deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create .ssh directory
      run: mkdir ~/.ssh && chmod 700 ~/.ssh
    - name: Place the key
      run: echo "${{ secrets.DEPLOY_KEY}}" > ~/.ssh/deployer && chmod 600 ~/.ssh/deployer
    - name: create known hosts
      run: echo "${{ secrets.KNOWN_HOSTS}}" > ~/.ssh/known_hosts
    - name: connect to deployer
      run: ssh -i ~/.ssh/deployer deployer@mypage.aadesh.site
    
    
      
      
     
