name: Build and deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: saadesh71/Profile@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: aadesh
        key: ${{ secrets.DEPLOY_KEY }}
        pass: ${{ secrets.DEPLOY_PASS }}
        script: |
          # git update to latest codebase on main branch
          echo ls
          # cd /path/to/project && git pull
          # # updating the .env file
          # cat <<EOF > ${{ secrets.ENVFILE_PATH }}
          # # start of envfile
          # DJANGO_SECRET_KEY=${{ secrets.ENVFILE_DJANGO_SECRET_KEY }}
          # # end of envfile
          # EOF
          # # see end result of envfile
          # ls -l ${{ secrets.ENVFILE_PATH }}
